# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#

DEFAULT_GOAL: uname

uname: uname.c
	gcc -o $@ $^

clean:
	rm -f uname
